# Generated by Django 3.1.1 on 2020-09-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_collumn', models.CharField(max_length=30)),
                ('int_collumn', models.IntegerField()),
                ('float_collumn', models.FloatField()),
                ('text_collumn', models.TextField(max_length=1000)),
            ],
        ),
    ]
